/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kz.zhanbolat.di;

import kz.zhanbolat.di.implinjection.ClientImplInjection;
import kz.zhanbolat.di.implinjection.ServiceImplInjection;
import kz.zhanbolat.di.injector.FieldDependencyInjector;
import kz.zhanbolat.di.interfacteinjection.Client;
import kz.zhanbolat.di.interfacteinjection.ServiceImpl;
import kz.zhanbolat.di.parentinjeciton.ClientChild;
import kz.zhanbolat.di.parentinjeciton.ServiceChild;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FieldDependencyInjectorTest {
    private FieldDependencyInjector dependencyInjector;

    @BeforeEach
    void setUp() {
        dependencyInjector = new FieldDependencyInjector();
    }

    @Test void appHasAGreeting() throws Exception {
        Client client = new Client();
        ServiceImpl service = new ServiceImpl();

        dependencyInjector.injectDependency("service", client, service);

        assertEquals(service, client.getService());
    }

    @Test
    void injectBasedOnImplementation() throws Exception {
        ClientImplInjection client = new ClientImplInjection();
        ServiceImplInjection service = new ServiceImplInjection();

        dependencyInjector.injectDependency("service", client, service);

        assertEquals(service, client.getService());
    }

    @Test
    void injectBasedOnParent() throws Exception {
        ClientChild client = new ClientChild();
        ServiceChild service = new ServiceChild();

        dependencyInjector.injectDependency("service", client, service);

        assertEquals(service, client.getService());
    }
}
